################################################
# Prognostic variables available for output
################################################
[prognostics.layerThickness]
dimensions = ["nVertLevels", "nCells", "time"]
units = "m"

[prognostics.normalVelocity]
dimensions = ["nVertLevels", "nEdges", "time"]
units = "m s-1"

[prognostics.ssh]
dimensions = ["nCells", "time"]
units = "m"

################################################
# Diagnostic variables available for output
################################################
[diagnostics]
[diagnostics.layerThicknessEdge]
dimensions = ["nVertLevels", "nEdges", "time"]
units = "m"

[diagnostics.layerThicknessVertex]
dimensions = ["nVertLevels", "nVertices", "time"]
units = "m"

[diagnostics.thicknessFlux]
dimensions = ["nVertLevels", "nEdges", "time"]
units = "m s-1"

[diagnostics.velocityDivCell]
dimensions = ["nVertLevels", "nCells", "time"]
units = "s-1"

[diagnostics.relativeVorticityVertex]
dimensions = ["nVertLevels", "nVertices", "time"]
units = "s-1"

[diagnostics.norm_rel_vort_vertex]
dimensions = ["nVertLevels", "nVertices", "time"]
units = "s-1 m-1"

[diagnostics.norm_rel_vort_edge]
dimensions = ["nVertLevels", "nEdges", "time"]
units = "s-1 m-1"

[diagnostics.norm_planet_vort_vertex]
dimensions = ["nVertLevels", "nVertices", "time"]
units = "s-1 m-1"

[diagnostics.norm_planet_vort_edge]
dimensions = ["nVertLevels", "nEdges", "time"]
units = "s-1 m-1"
